name: coalition_mobile_app
description: Mobile coalition app for candidate discovery, events, and admin tooling.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^3.0.0
  equatable: ^2.0.5
  go_router: ^16.2.2
  uuid: ^4.4.0
  share_plus: ^12.0.0
  url_launcher: ^6.2.6
  google_sign_in: ^7.2.0
  shared_preferences: ^2.2.3
  crypto: ^3.0.3
  image_picker: ^1.0.7
  video_player: ^2.8.2
  video_thumbnail: ^0.5.3
  photo_manager: ^3.7.1
  better_player: ^0.0.88
  connectivity_plus: ^6.0.3
  ffmpeg_kit_flutter_min_gpl: ^6.0.3
  path_provider: ^2.1.3
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample/
